CREATE TABLE IF NOT EXISTS "company_profile" (
  "id" INTEGER PRIMARY KEY CHECK (id = 1),
  "name" TEXT,
  "type" TEXT,
  "vat" TEXT,
  "customs_code" TEXT,
  "iban" TEXT,
  "phone" TEXT,
  "phone_code" TEXT,
  "fax" TEXT,
  "email" TEXT,
  "address" TEXT,
  "address_street" TEXT,
  "address_postal" TEXT,
  "address_city" TEXT,
  "logo" TEXT,
  "logo_path" TEXT,
  "seal_enabled" INTEGER,
  "seal_image" TEXT,
  "seal_max_width_mm" REAL,
  "seal_max_height_mm" REAL,
  "seal_opacity" REAL,
  "seal_rotate_deg" REAL,
  "signature_enabled" INTEGER,
  "signature_image" TEXT,
  "signature_rotate_deg" REAL,
  "lan_enabled" INTEGER,
  "lan_port" INTEGER,
  "lan_redirect_http80" INTEGER,
  "updated_at" TEXT
);

